FROM node:20-alpine as builder

WORKDIR /usr/src/app

COPY package.json package-lock.json ./

RUN npm install -g create-vite
RUN npm install -g vite

RUN npm install

COPY . .

RUN npm run build

FROM node:20-alpine

WORKDIR /usr/src/app

COPY --from=builder /usr/src/app/dist ./dist
COPY --from=builder /usr/src/app/package.json ./
COPY --from=builder /usr/src/app/package-lock.json ./

RUN npm install 

EXPOSE 4173

CMD ["npm", "run", "preview"]
