# Use uma imagem MySQL oficial do Docker Hub
FROM mysql:5.7

# Exponha a porta padrão do MySQL
EXPOSE 3306

# Copie o script SQL para ser executado durante a inicialização
COPY ./init.sql /docker-entrypoint-initdb.d/
