CREATE DATABASE IF NOT EXISTS notesdb;
CREATE TABLE IF NOT EXISTS `notesdb`.`users` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(255) NOT NULL,
    `username` VARCHAR(255) NOT NULL,
    `password` VARCHAR(255) NOT NULL
);
